# Generated by Django 4.2.7 on 2024-01-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='Bug',
        ),
    ]
