# Generated by Django 4.2.7 on 2024-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('field', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('announcement', models.TextField()),
            ],
        ),
    ]
