# Generated by Django 4.2.7 on 2024-01-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('application_data', models.TextField()),
            ],
        ),
    ]
