# Generated by Django 4.2.7 on 2024-01-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_data',
            new_name='data',
        ),
    ]
